title: Experiential Learning for Cyber Security Education
description: "Explore, learn, and test your cyber security skills through fun, hands-on challenges!
This website is part of a research study that aims to understand how 
interactive activities like Capture the Flag (CTF) can help high school students learn 
cyber security concepts in engaging and practical ways."

header_button:
  text: "Start Challenges"
  url: "/challenges/"


# PROJECT site settings
url: https://wicksl08.github.io  # <-- replace YOUR-USERNAME (no trailing slash)
baseurl: "/ExForCyberEducation"                    # <-- replace with your repo name, with leading slash

# Fun, clean theme supported by Pages
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation (links auto-prefix with baseurl)
nav:
  - title: Home
    url: /
    - title: About
    url: /about/
     - title: Learning
    url: /learning/
  - title: Challenges
    url: /challenges/
  - title: Teachers
    url: /teachers/
  
 



# SEO
description: "Capture-the-Flag style cyber security learning, mapped to Alabama K-12 standards."
include:
  - assets/css/custom.css

